In [2]:
# In[1]: 
import numpy as np

# In[2]: Create a NumPy array
data = np.array([10, 20, 30, 40, 50])
print("Array:", data)

# In[3]: Perform element-wise operations
print("Array multiplied by 2:", data * 2)
print("Array squared:", data ** 2)

# In[4]: Compute basic statistics
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))
print("Sum:", np.sum(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

# In[5]: Create a 2D array (matrix)
matrix = np.array([[1, 2], [3, 4]])
print("2D Matrix:\n", matrix)

# In[6]: Matrix operations
print("Transpose:\n", matrix.T)
print("Dot product:\n", np.dot(matrix, matrix))

Array: [10 20 30 40 50]
Array multiplied by 2: [ 20  40  60  80 100]
Array squared: [ 100  400  900 1600 2500]
Mean: 30.0
Standard Deviation: 14.142135623730951
Sum: 150
Max: 50
Min: 10
2D Matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]
Dot product:
 [[ 7 10]
 [15 22]]


In [3]:
print("Array:", data)

Array: [10 20 30 40 50]
